### ISSUE TITLE
Uncaught Error: Could not initialize the SDK :: no storage is available (Incognito)

### ISSUE THREAD

**Issue by Grisgruis** [rudderlabs/rudder-sdk-js#447] opened 2022-02-08 20:45 UTC
When i'm including the rudderstack sdk inside an iframed project the javascript fails to load in an incognito window

**Expected:**
The sdk to load fine, also in incognito mode (at least fallbacking to some kind of in memory storage?)

**Result:**
SDK fails to load inside an https iframe in incognito mode.

The error on itself is not much of a problem, but for my application I load the sdk with npm.  And  when I add and use the line  `import * as rudderanalytics from 'rudder-sdk-js';` my application stops working (in https iframe), which is kinda odd. even when I don't hit the `load` code.

**How to reproduce:**
In Chrome 96.0.4664.110 open incognito window and load the html below inside an iframe (make sure over https, localhost seems to work fine(?))

```
<html>
<head>
<script type="text/javascript">
document.body.innerHTML = "Broken :(";
!function(){var e=window.rudderanalytics=window.rudderanalytics||[];e.methods=["load","page","track","identify","alias","group","ready","reset","getAnonymousId","setAnonymousId"],e.factory=function(t){return function(){var r=Array.prototype.slice.call(arguments);return r.unshift(t),e.push(r),e}};for(var t=0;t<e.methods.length;t++){var r=e.methods[t];e[r]=e.factory(r)}e.loadJS=function(e,t){var r=document.createElement("script");r.type="text/javascript",r.async=!0,r.src="https://cdn.rudderlabs.com/v1/rudder-analytics.min.js";var a=document.getElementsByTagName("script")[0];a.parentNode.insertBefore(r,a)},e.loadJS(),
e.load('24qKyUhZbkqs3s77vFvEpLWi4JM','https://smartlazclcl.dataplane.rudderstack.com'),
e.ready(() => {document.body.innerHTML = "Working! :)"})}();
</script>
</head><body><div></div></body></html>
```

See example: (open it in incognito window(!)) and see console throws a `Uncaught Error: Could not initialize the SDK :: no storage is available`
https://jsfiddle.net/z68w0q1y/2/

Which embeds the html above (https://jsfiddle.net/5x0csrov/4/)

Any insights on this?

**Comment by MoumitaM** [comment] 2022-02-09 12:47
Hi @Grisgruis,

This is an expected behaviour when cookie or local storage is not accessible. Because without storage the SDK might not work properly.

**Comment by PeterDeKok** [comment] 2022-02-10 10:06
Can be reproduced with these commands:

```bash 
mkdir test-rudder-sdk-storage-unavailable \
&& cd test-rudder-sdk-storage-unavailable \
&& yarn init -y \
&& yarn add rudder-sdk-js@1.3.4 \
&& yarn add -D rollup@2.67.1 @rollup/plugin-node-resolve@13.1.3 \
&& echo "import * as rudderanalytics from 'rudder-sdk-js';console.log('will we get here?');console.debug(rudderanalytics);" > index.js \
&& echo '<!DOCTYPE html><html><head><script src="./index.build.js"></script></head><body>Rudder SDK JS</body></html>' > index.html \
&& ./node_modules/.bin/rollup index.js --format iife --output.file ./index.build.js --plugin @rollup/plugin-node-resolve \
&& open index.html
```

The last operation (open) should be performed with a browser that has cookies & localstorage disabled.

E.g. 
For example, I have a chrome profile which basically blocks everything.
The relevant settings are [chrome://settings/cookies](chrome://settings/cookies) -> Block all cookies (not recommended)

Chrome Version 96.0.4664.110 (Official Build) (x86_64)

---

This will result in the console log not triggering, due to a thrown error:

```text
Uncaught Error: Could not initialize the SDK :: no storage is available
    at new Storage (index.build.js:11672)
    at index.build.js:11950
    at index.build.js:7
    at index.build.js:8
    at index.build.js:38474
```

**Comment by MoumitaM** [comment] 2022-02-17 07:13
@PeterDeKok,
You can use dynamic import and use the try/catch.
Although I don’t see any benefits of using Rudderstack's JS SDK if it is not initialized. 

Otherwise, you can use Rudderstacks HTTP API.

**Comment by Grisgruis** [comment] 2022-02-17 09:14
@MoumitaM Iam not sure you understand the problem, yes we can work around with a whole lot of options. But we are using basic examples from your documentation. I don't think it should be a 'feature' that someone's application breaks when using the rudderstack SDK.

The use case we are sketching here is, follow the docs, use the rudderstack SDK, open your application in a framed window, and the application won't boot due to rudderstack SDK throwing errors. That's the problem.

We can workaround but I don't think this is a 'feature' you should keep

**Comment by saikumarrs** [comment] 2022-02-17 10:24
@Grisgruis Apologies for any confusion created. One thing that I want to clarify here is that we do not want to proceed with the SDK processing if none of the storage options are available. Otherwise, the SDK behavior would be inconsistent.

Thanks for all the feedback provided here. We'll go back and work on finding a better solution to this problem.

**Comment by saikumarrs** [comment] 2022-03-03 07:52
We've now updated the SDK to throw errors in the `load` method rather than during the SDK initialization. Hence, closing this issue.

**Closed by saikumarrs** 2022-03-03 07:52 UTC
