### ISSUE TITLE
Feature Request: avoid using `unload` event listener to enable bfcache

### ISSUE THREAD

**Issue by dfrico** [rudderlabs/rudder-sdk-js#1175] opened 2023-06-22 14:35 UTC
### Is your feature request related to a problem? Please describe.

Hi! I believe [this line here](https://github.com/rudderlabs/rudder-sdk-js/blob/26e0d68ae4a7a68ffd45cbbd8985b1b06ea43924/src/utils/beaconQueue.js#LL34C8-L34C8) 

```
window.addEventListener('unload', sendQueueData);
```

may be the cause of performance issues described [here](https://web.dev/bfcache/), more specifically:

> The most important way to optimize for bfcache in all browsers is to never use the unload event.

### Describe the solution you'd like
I don't know if it helps, but this same page suggests an alternative approach:

> Instead of using the `unload` event, use the `pagehide` event. The pagehide event fires in all cases where the unload event currently fires, and it also fires when a page is put in the bfcache.

I would love to understand the context behind this `unload` eventListener used in `BeaconQueue` so that I can try and solve this issue.

Thank you for your time!

**Describe alternatives you've considered**
No other alternatives yet.

**Additional context**
This issue is also raised by lighthouse:

<img width="715" alt="image" src="https://github.com/rudderlabs/rudder-sdk-js/assets/7013170/89606972-a61b-468f-a04e-f27c422ec1db">

**Comment by bardisg** [comment] 2023-06-26 08:12
Hello @dfrico,

Thank you for your feedback.

Your concers have valid grounds and we will be looking into changing into using 'visibilitychange' events soon and replace existing outdated mechanism.

We will communicate a timeline for this soon.

**Comment by bardisg** [comment] 2023-06-30 06:59
Hello @dfrico,

Our nex release should resolve the issue you are facing.

**Comment by dfrico** [comment] 2023-06-30 08:23
Hey @bardisg, that's great, thank you! Looking forward to trying the new release 👍🏻 cheers!

**Comment by MoumitaM** [comment] 2023-07-11 03:57
Hi @dfrico, We have released a new version of the SDK. Try it out and let us know your feedback.

**Comment by dfrico** [comment] 2023-07-12 14:28
Looks good, thanks a lot for the quick fix!

**Comment by saikumarrs** [comment] 2023-07-24 05:36
@dfrico, I believe the issue is addressed. Hence, closing the this.

**Closed by saikumarrs** 2023-07-24 05:36 UTC
Labels: open source
