### ISSUE TITLE
BUG : Native crypto module could not be used to get secure random number.

### ISSUE THREAD

**Issue by abbbel2** [rudderlabs/rudder-sdk-js#1580] opened 2024-01-09 14:36 UTC
**Describe the bug**
while invoking the getAnonymousId method, it's throwing an error "Native crypto module could not be used to get secure random number."

**To Reproduce**
call the getAnonymousId method

**Expected behavior**
The above error should not appear

**Screenshots**

**Additional Information (please complete the following information):**

- NPM Version: 2.47.0
- Used JS Framework Reactjs

**Comment by MoumitaM** [comment] 2024-01-09 15:16
@abbbel2 Can you share a website where this is happening?
It is not reproducible.

**Comment by MoumitaM** [comment] 2024-02-02 08:13
Closing this issue since there is no communication and it is not reproducible.

**Closed by MoumitaM** 2024-02-02 08:13 UTC
Labels: bug, open source
